[project]
name = "houses-ms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.129.0",
    "psycopg>=3.3.2",
    "pydantic-settings>=2.13.0",
    "python-dotenv>=1.2.1",
    "sqlmodel>=0.0.34",
]
